FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine AS build
WORKDIR /app

COPY "HelloWorld.csproj" .
RUN dotnet restore --runtime linux-musl-x64 
COPY . .
RUN dotnet build "HelloWorld.csproj" --no-restore -c Release --runtime linux-musl-x64 

FROM build AS publish

RUN dotnet publish "HelloWorld.csproj" \
  --no-restore \
  --no-build \
  -c Release \
  --runtime linux-musl-x64 \
  -o ./publish
  
FROM mcr.microsoft.com/dotnet/runtime:8.0-alpine AS final
WORKDIR /app

COPY --from=publish /app/publish .
ENTRYPOINT [ "./HelloWorld"]
CMD [ "from", "entrypoint with cmd combo" ]